name: Build Game Packages

on:
  push:
    tags:
      - 'v*'  # Run when a tag is pushed with format v1.0.0, etc.

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            asset_name: SpaceConquer-Linux
          - os: windows-latest
            asset_name: SpaceConquer-Windows
          - os: macos-latest
            asset_name: SpaceConquer-macOS

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame numpy pyinstaller
        
    - name: Build with PyInstaller (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --name=SpaceConquer --onefile --windowed --icon=images/player_ship.png --add-data="images;images" --add-data="sounds;sounds" --add-data="music;music" main.py
        
    - name: Build with PyInstaller (macOS/Linux)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --name=SpaceConquer --onefile --windowed --icon=images/player_ship.png --add-data="images:images" --add-data="sounds:sounds" --add-data="music:music" main.py
        
    - name: Create Release Package (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir -p release
        cp dist/SpaceConquer.exe release/
        cp README.md LICENSE CHANGELOG.md release/
        cd release
        7z a -tzip "../${{ matrix.asset_name }}.zip" *
        
    - name: Create Release Package (macOS/Linux)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p release
        cp dist/SpaceConquer release/
        cp README.md LICENSE CHANGELOG.md release/
        echo '#!/bin/bash' > release/run_game.sh
        echo 'chmod +x ./SpaceConquer' >> release/run_game.sh
        echo './SpaceConquer' >> release/run_game.sh
        chmod +x release/run_game.sh
        cd release
        zip -r "../${{ matrix.asset_name }}.zip" *
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
